version: '3'

includes:
  terraform:
    taskfile: https://raw.githubusercontent.com/soltiHQ/actions/v1/taskfiles/terraform/Taskfile.yml
  node:
    taskfile: https://raw.githubusercontent.com/soltiHQ/actions/v1/taskfiles/node/Taskfile.yml
  aws:
    taskfile: https://raw.githubusercontent.com/soltiHQ/actions/v1/taskfiles/aws/Taskfile.yml

tasks:
  run/dev:
    desc: "Run dev environment"
    cmds:
      - task: node:_npm/tool
        vars:
          CMD: "sh -c 'npm install && npm run optimize-images && exec ./node_modules/.bin/vite --host 0.0.0.0 --port 5173'"

  ci/build:
    desc: "Run build static"
    cmds:
      - task: node:_npm/tool
        vars:
          CMD: "sh -c 'npm ci && npm run optimize-images && npm run type-check && npm run build'"

  ci/audit:
    desc: "Run dependencies audit"
    cmds:
      - task: node:audit

  ci/terraform-fmt:
    desc: "Run terraform fmt check"
    cmds:
      - task: terraform:fmt

  ci/terraform-validate:
    desc: "Run terraform validation"
    cmds:
      - task: terraform:validate

  cd/terraform-apply:
    requires:
      vars: [ TF_BACKEND_BUCKET, TF_BACKEND_KEY, TF_BACKEND_REGION ]
    cmds:
      - task: terraform:apply
        vars:
          BACKEND_BUCKET: '{{.TF_BACKEND_BUCKET}}'
          BACKEND_REGION: '{{.TF_BACKEND_REGION}}'
          BACKEND_KEY: '{{.TF_BACKEND_KEY}}'

  cd/deploy:
    requires:
      vars: [ SITE_BUCKET_NAME, CLOUDFRONT_DISTRIBUTION_ID ]
    cmds:
      - task: aws:s3/publish
        vars:
          SOURCE_DIR: app/dist
          BUCKET: '{{.SITE_BUCKET_NAME}}'
      - task: aws:cloudfront/invalidate
        vars:
          DISTRIBUTION_ID: '{{.CLOUDFRONT_DISTRIBUTION_ID}}'
