name: Checks

on:
  workflow_call:
    secrets:
      gitleaks: 
        required: true

jobs:
  terraform:
    name: Terraform 
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Invoke
        uses: Mad-Pixels/github-workflows/actions/taskfile-runner@dev3
        with:
          command: terraform/fmt

  eslint:
    name: ESLint
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Invoke
        uses: Mad-Pixels/github-workflows/actions/taskfile-runner@dev3
        with:
          command: node/lint

  prettier:
    name: Prettier
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Invoke
        uses: Mad-Pixels/github-workflows/actions/taskfile-runner@dev3
        with:
          command: node/format

  audit: 
    name: Audit 
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Invoke
        uses: Mad-Pixels/github-workflows/actions/taskfile-runner@dev3
        with:
          command: node/audit
  
  leaks:
    name: GitLeaks
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.gitleaks }}

  type-check:
    name: TypeCheck
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Invoke
        uses: Mad-Pixels/github-workflows/actions/taskfile-runner@dev3
        with:
          command: node/type-check
        
