name: Create tag

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create (e.g., v1.0.0)'
        required: true
        type: string
      force:
        description: 'Force overwrite existing tag'
        required: false
        type: boolean
        default: false

concurrency:
  group: manual-tag-${{ inputs.tag }}
  cancel-in-progress: true

jobs:
  create-tag:
    name: Create Tag
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: Invoke
        uses: Mad-Pixels/github-workflows/.github/actions/github-create-tag@main
        with:
          tag: ${{ inputs.tag }}
          force: ${{ inputs.force }}
          token: ${{ secrets.PAT_TOKEN }}
