name: PR label

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

concurrency:
  group: pr-label-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  label-check:
    name: Label check
    uses: mr-chelyshkin/actions/.github/workflows/require-changelog-label.yml@v1
