name: Publish Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: release-tag-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  check-main-branch:
    name: Verify tag from main branch
    runs-on: ubuntu-latest
    steps:
      - name: Invoke
        uses: Mad-Pixels/github-workflows/.github/actions/github-check-branch@main
        with:
          tag_name: ${{ github.ref_name }}

  apply:
    needs: check-main-branch
    uses: ./.github/workflows/.terraform.yml
    name: (Release) Apply
    with:
      tf_command: "apply"
    secrets:
      aws_access_key:     ${{ secrets.AWS_ACCESS_KEY_MAIN }}
      aws_secret_key:     ${{ secrets.AWS_SECRET_KEY_MAIN }}
      aws_region:         ${{ secrets.AWS_REGION }}

      aws_backend_bucket: ${{ secrets.AWS_BACKEND_BUCKET }}
      aws_backend_region: ${{ secrets.AWS_BACKEND_REGION }}
      aws_backend_key:    ${{ secrets.AWS_BACKEND_KEY }}

      acm_crt:            ${{ secrets.ACM_CRT }}
      bucket_name:        ${{ secrets.SITE_BUCKET_NAME }}